# Generated by Django 5.0.7 on 2024-12-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GrillGuard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bill_number",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
